# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'game_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import battle_pb2 as battle__pb2
import game_pb2 as game__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12game_service.proto\x12\x0cgame_service\x1a\x0c\x62\x61ttle.proto\x1a\ngame.proto\"K\n\x10RoomDetailNotify\x12\x17\n\x0f\x62\x65_notified_uid\x18\x01 \x01(\x04\x12\x1e\n\x04room\x18\x02 \x01(\x0b\x32\x10.game.RoomDetail2\xf3\x01\n\x0eGameRpcService\x12M\n\x13RoomStatusNotifyRpc\x12\x1e.game_service.RoomDetailNotify\x1a\x16.battle.NotifyResponse\x12\x45\n\x12GameStateNotifyRpc\x12\x17.battle.GameStateNotify\x1a\x16.battle.NotifyResponse\x12K\n\x15PlayerActionNotifyRpc\x12\x1a.battle.PlayerActionNotify\x1a\x16.battle.NotifyResponseB\x12Z\x10server/src/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020server/src/proto'
  _globals['_ROOMDETAILNOTIFY']._serialized_start=62
  _globals['_ROOMDETAILNOTIFY']._serialized_end=137
  _globals['_GAMERPCSERVICE']._serialized_start=140
  _globals['_GAMERPCSERVICE']._serialized_end=383
# @@protoc_insertion_point(module_scope)
