# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: match.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'match.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_pb2 as game__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmatch.proto\x12\x05match\x1a\ngame.proto\"C\n\x0bMatchResult\x12\x1c\n\x03ret\x18\x01 \x01(\x0e\x32\x0f.game.ErrorCode\x12\x16\n\x0eresult_message\x18\x02 \x01(\t\"N\n\x0eSSMatchRequest\x12\x11\n\tplayer_id\x18\x01 \x01(\x04\x12)\n\x0bplayer_data\x18\x02 \x01(\x0b\x32\x14.game.PlayerInitData\"^\n\x0fSSMatchResponse\x12\x1c\n\x03ret\x18\x01 \x01(\x0e\x32\x0f.game.ErrorCode\x12\x11\n\tbattle_id\x18\x02 \x01(\t\x12\x1a\n\x12\x62\x61ttle_server_addr\x18\x03 \x01(\t\"X\n\x13SSMatchResultNotify\x12.\n\x0fmatched_players\x18\x01 \x03(\x0b\x32\x15.match.SSMatchRequest\x12\x11\n\tbattle_id\x18\x02 \x01(\t2K\n\x0cMatchService\x12;\n\nStartMatch\x12\x15.match.SSMatchRequest\x1a\x16.match.SSMatchResponse2X\n\x14InternalMatchService\x12@\n\x0eOnMatchSuccess\x12\x1a.match.SSMatchResultNotify\x1a\x12.match.MatchResultB\x12Z\x10server/src/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'match_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020server/src/proto'
  _globals['_MATCHRESULT']._serialized_start=34
  _globals['_MATCHRESULT']._serialized_end=101
  _globals['_SSMATCHREQUEST']._serialized_start=103
  _globals['_SSMATCHREQUEST']._serialized_end=181
  _globals['_SSMATCHRESPONSE']._serialized_start=183
  _globals['_SSMATCHRESPONSE']._serialized_end=277
  _globals['_SSMATCHRESULTNOTIFY']._serialized_start=279
  _globals['_SSMATCHRESULTNOTIFY']._serialized_end=367
  _globals['_MATCHSERVICE']._serialized_start=369
  _globals['_MATCHSERVICE']._serialized_end=444
  _globals['_INTERNALMATCHSERVICE']._serialized_start=446
  _globals['_INTERNALMATCHSERVICE']._serialized_end=534
# @@protoc_insertion_point(module_scope)
